version: 2.1

executors:
  default:
    docker:
      - image: stackfeed/circle-shell

workflows:
  version: 2.0
  default:
    jobs:
      - alpine

commonEnv: &commonEnv
  PUSH_NAMESPACES: dennybaa

jobs:
  alpine:
    executor: default
    environment:
      <<: *commonEnv
      DBTAG_FLAVOUR: alpine
      DBTAG_LATEST: 1.12
      DOCKERFILE: alpine.Dockerfile

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install tools
          command: |
            curl -sL https://git.io/dbtag | sudo bash -s -- /usr/local/bin

      - run:
          name: Build
          command: |
            export DBTAG_FLAVOUR=$CIRCLE_JOB
            docker image build -t golang-dev -f ${DOCKERFILE} ./

      - run:
          name: Publish
          command: |
            # # skip publish when non a non-realease tag or branch met
            # if [[ $CIRCLE_TAG == "" ]] || ![[ $CIRCLE_TAG =~ ^v[0-9]. ]]; then exit 0; fi

            semver=$(docker run -t golang-dev go version | sed -n 's/.*go\(.*\) .*/\1/p')
            dbtag $semver golang-dev ${PUSH_NAMESPACES}/golang-dev
            echo Publishing Yo
